/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.ScocciaMatteo119748.implementation;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.println("\nLOGO INSTRUCTION EXECUTER\n");
        Controller controller = new Controller(new ConsoleView());
        controller.exec();
    }
}
